/// GENERATED by scripts/canonicality-battery.sh from `frontier_oracle canonical `.
/// Source of truth: ark_bls12_381::Fr deserialize_compressed. DO NOT EDIT BY HAND --
/// an edit here would let a real divergence pass. Regenerate instead.
module {
  public let corpus : [(Text, Text, Bool)] = [
    ("zero", "0000000000000000000000000000000000000000000000000000000000000000", true),
    ("one", "0100000000000000000000000000000000000000000000000000000000000000", true),
    ("p_minus_one_le", "00000000fffffffffe5bfeff02a4bd5305d8a10908d83933487d9d2953a7ed73", true),
    ("p_le", "01000000fffffffffe5bfeff02a4bd5305d8a10908d83933487d9d2953a7ed73", false),
    ("p_plus_one_le", "02000000fffffffffe5bfeff02a4bd5305d8a10908d83933487d9d2953a7ed73", false),
    ("all_ff", "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", false),
    ("p_be", "73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001", true),
    ("random_canonical", "e825ff8f4f0d4d3b4231123c9d7845c543ea83f05d3e65f98e3e1f4ffd135f54", true),
    ("short", "00", false),
    ("odd_nibbles", "000000000000000000000000000000000000000000000000000000000000000", false),
  ];
}
