/// Differential gate for `src/PoseidonTree.mo` against the arkworks oracle fixtures
/// (`FrontierVectorsA/B.mo`, generated by `frontier_oracle`). Runs as a WASI
/// program (moc -wasi-system-api, wasmtime). Traps on the FIRST divergence with its
/// coordinates; prints per-family and total comparison counts on success.
/// Menese DeFi Team.

import Prim "mo:⛔";
import Runtime "mo:core/Runtime";
import Nat "mo:core/Nat";
import Nat64 "mo:core/Nat64";
import P "../src/PoseidonTree";
import A "FrontierVectorsA";
import B "FrontierVectorsB";

var total : Nat = 0;

func check(family : Text, index : Nat, got : Nat, expected : Nat) {
  if (got != expected) {
    Runtime.trap(
      "DIVERGENCE " # family # "[" # Nat.toText(index) # "]: got "
      # Nat.toText(got) # " expected " # Nat.toText(expected)
    );
  };
  total += 1;
};

func checkText(family : Text, index : Nat, got : Text, expected : Text) {
  if (got != expected) {
    Runtime.trap("DIVERGENCE " # family # "[" # Nat.toText(index) # "]: got " # got # " expected " # expected);
  };
  total += 1;
};

func runFixture(
  name : Text,
  perm : [(Nat, Nat, Nat, Nat, Nat, Nat)],
  hashN : [([Nat], Nat)],
  compress : [(Nat, Nat, Nat)],
  zeros : [Nat],
  zerosHex : [Text],
  seqLeaves : [Nat],
  seqRoots : [Nat],
  seqRootsHex : [Text],
  denseCheck : [(Nat, Nat)],
  synth : [([Nat], Nat, [Nat], [Nat], Nat, Nat, Text)],
) {
  let base = total;

  // raw permutation
  var i : Nat = 0;
  for ((i0, i1, i2, o0, o1, o2) in perm.vals()) {
    let (g0, g1, g2) = P.permute(i0, i1, i2);
    check(name # ".perm.0", i, g0, o0);
    check(name # ".perm.1", i, g1, o1);
    check(name # ".perm.2", i, g2, o2);
    i += 1;
  };

  // sponge hash_n
  i := 0;
  for ((inputs, expected) in hashN.vals()) {
    check(name # ".hashN", i, P.hashN(inputs), expected);
    i += 1;
  };

  // merkle compress
  i := 0;
  for ((l, r, expected) in compress.vals()) {
    check(name # ".compress", i, P.merkleCompress(l, r), expected);
    i += 1;
  };

  // zero hashes (computed in-module, compared value- and hex-level)
  let z = P.zeroHashes();
  if (z.size() != zeros.size()) { Runtime.trap(name # ": zeros size") };
  i := 0;
  while (i < zeros.size()) {
    check(name # ".zeros", i, z[i], zeros[i]);
    checkText(name # ".zerosHex", i, P.natToHex(z[i]), zerosHex[i]);
    i += 1;
  };

  // sequential frontier from the empty tree
  var frontier = P.emptyFrontier(z);
  i := 0;
  while (i < seqLeaves.size()) {
    let (next, root) = P.append(frontier, z, seqLeaves[i]);
    frontier := next;
    check(name # ".seqRoot", i, root, seqRoots[i]);
    checkText(name # ".seqRootHex", i, P.natToHex(root), seqRootsHex[i]);
    if (Nat64.toNat(frontier.nextIndex) != i + 1) { Runtime.trap(name # ": nextIndex drift") };
    i += 1;
  };

  // DenseTree (independent full recompute) spot checks
  i := 0;
  for ((leafCount, expected) in denseCheck.vals()) {
    check(name # ".dense", i, seqRoots[leafCount - 1], expected);
    i += 1;
  };

  // synthetic frontiers: arbitrary filled/nextIndex, 1-2 appends
  i := 0;
  for ((filledIn, nextIn, leaves, filledOut, nextOut, rootOut, rootOutHex) in synth.vals()) {
    var f : P.Frontier = { filled = filledIn; nextIndex = Nat64.fromNat(nextIn) };
    var root : Nat = 0;
    for (leaf in leaves.vals()) {
      let (nf, r) = P.append(f, z, leaf);
      f := nf;
      root := r;
    };
    var level : Nat = 0;
    while (level < 32) {
      check(name # ".synthFilled." # Nat.toText(level), i, f.filled[level], filledOut[level]);
      level += 1;
    };
    check(name # ".synthNext", i, Nat64.toNat(f.nextIndex), nextOut);
    check(name # ".synthRoot", i, root, rootOut);
    checkText(name # ".synthRootHex", i, P.natToHex(root), rootOutHex);
    i += 1;
  };

  // hex codec roundtrip + rejection paths on fixture data
  i := 0;
  for ((_, _, expected) in compress.vals()) {
    switch (P.hexToNat(P.natToHex(expected))) {
      case (?back) check(name # ".hexRoundtrip", i, back, expected);
      case null Runtime.trap(name # ": hex roundtrip returned null at " # Nat.toText(i));
    };
    switch (P.blobToNat(P.natToBlob(expected))) {
      case (?back) check(name # ".blobRoundtrip", i, back, expected);
      case null Runtime.trap(name # ": blob roundtrip returned null at " # Nat.toText(i));
    };
    i += 1;
  };
  // non-canonical (r, little-endian) and malformed inputs must be rejected
  if (P.hexToNat("01000000fffffffffe5bfeff02a4bd5305d8a10908d83933487d9d2953a7ed73") != null) {
    Runtime.trap(name # ": modulus accepted as canonical");
  };
  if (P.hexToNat("00") != null) { Runtime.trap(name # ": short hex accepted") };
  if (P.hexToNat("zz000000000000000000000000000000000000000000000000000000000000zz") != null) {
    Runtime.trap(name # ": bad digits accepted");
  };
  total += 3;

  Prim.debugPrint(name # ": " # Nat.toText(total - base) # " comparisons green");
};

runFixture(
  "seedA", A.perm, A.hashN, A.compress, A.zeros, A.zerosHex,
  A.seqLeaves, A.seqRoots, A.seqRootsHex, A.denseCheck, A.synth,
);
runFixture(
  "seedB", B.perm, B.hashN, B.compress, B.zeros, B.zerosHex,
  B.seqLeaves, B.seqRoots, B.seqRootsHex, B.denseCheck, B.synth,
);

Prim.debugPrint("PASS PoseidonDifferential: " # Nat.toText(total) # " total byte-identical comparisons");
